server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
#  profiles:
#    active: @spring.profiles.active@
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-181381.okta.com/oauth2/default