server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
#  security:
#    oauth2:
#      client:
#        registration:
#          okta:
#            client-id: replace-me
#            client-secret: replace-me
#        provider:
#          okta:
#            issuer-uri: replace-me