spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: replace-me
            client-secret: replace-me
        provider:
          okta:
            issuer-uri: https://dev-181381.okta.com/oauth2/default